PATH_TO_MODEL: "/Model"
answer_serv: "https://llm.api.cloud.yandex.net/llm/v1alpha/instruct"
interface_serv: "devxpy/cog-wav2lip:8d65e3f4f4298520e079198b493c25adfc43c058ffec924f2aefc8010ed25eef"
PATH_TO_OUTPUT: "/materials/audio"
PATH_TO_OUTPUT_AUD: "/materials/audio/output.wav"
PATH_VID: "/materials/video.mp4"
PATH_AUD: "/materials/audio/output.wav"
width: 640
height: 480
FPS: 25
path_to_static: "/materials/Volya.jpg"
